# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2d744562e893d47e2da820db82d6ad1111c358d7a3f105288826f1b47c60b403a39dd819c9486d39c28e01de5ff7453e426c392f00512d09dc59774462823f6

test:
  secret_key_base: ed5e5c4258c123d29b114a63f84d992e4cebedcd18fb1ff173f6f50c8e658c71242ab9947f058dc6cf21d54363fab284acca85c0f0ce57e91225fbb9e30f1b5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
